import 'package:isar/isar.dart';

part 'modality.g.dart';

@Collection()
class Modality {
  final Id? id;
  final String namePt;
  final String nameEn;
  final String nameEs;
  final String? status; // 'A', 'B', 'I', 'P'
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const Modality({
    this.id,
    required this.nameEn,
    required this.nameEs,
    required this.namePt,
    this.status,
    this.createdAt,
    this.updatedAt
  });

  static List<Modality> modalities = [
    Modality(id: 1, namePt: 'Musculação', nameEn: 'Bodybuilding', nameEs: 'Musculación', status: 'A'),
    Modality(id: 2, namePt: 'Treinamento Funcional', nameEn: 'Functional Training', nameEs: 'Entrenamiento Funcional', status: 'A'),
    Modality(id: 3, namePt: 'Yoga', nameEn: 'Yoga', nameEs: 'Yoga', status: 'A'),
    Modality(id: 4, namePt: 'Pilates', nameEn: 'Pilates', nameEs: 'Pilates', status: 'A'),
    Modality(id: 5, namePt: 'CrossFit', nameEn: 'CrossFit', nameEs: 'CrossFit', status: 'A'),
    Modality(id: 6, namePt: 'Calistenia', nameEn: 'Calisthenics', nameEs: 'Calistenia', status: 'A'),
    Modality(id: 7, namePt: 'Spinning', nameEn: 'Spinning', nameEs: 'Spinning', status: 'A'),
    Modality(id: 8, namePt: 'HIIT', nameEn: 'HIIT', nameEs: 'HIIT', status: 'A'),
    Modality(id: 9, namePt: 'Corrida', nameEn: 'Running', nameEs: 'Correr', status: 'A'),
    Modality(id: 10, namePt: 'Caminhada', nameEn: 'Walking', nameEs: 'Caminata', status: 'A'),
    Modality(id: 11, namePt: 'Alongamento', nameEn: 'Stretching', nameEs: 'Estiramiento', status: 'A'),
    Modality(id: 12, namePt: 'Mobilidade Articular', nameEn: 'Joint Mobility', nameEs: 'Movilidad Articular', status: 'A'),
    Modality(id: 13, namePt: 'Zumba', nameEn: 'Zumba', nameEs: 'Zumba', status: 'A'),
    Modality(id: 14, namePt: 'Step', nameEn: 'Step', nameEs: 'Step', status: 'A'),
    Modality(id: 15, namePt: 'Jump', nameEn: 'Jump', nameEs: 'Jump', status: 'A'),
    Modality(id: 16, namePt: 'Boxe', nameEn: 'Boxing', nameEs: 'Boxeo', status: 'A'),
    Modality(id: 17, namePt: 'Muay Thai', nameEn: 'Muay Thai', nameEs: 'Muay Thai', status: 'A'),
    Modality(id: 18, namePt: 'Jiu-Jitsu', nameEn: 'Jiu-Jitsu', nameEs: 'Jiu-Jitsu', status: 'A'),
    Modality(id: 19, namePt: 'Judô', nameEn: 'Judo', nameEs: 'Judo', status: 'A'),
    Modality(id: 20, namePt: 'Karatê', nameEn: 'Karate', nameEs: 'Karate', status: 'A'),
    Modality(id: 21, namePt: 'Taekwondo', nameEn: 'Taekwondo', nameEs: 'Taekwondo', status: 'A'),
    Modality(id: 22, namePt: 'Capoeira', nameEn: 'Capoeira', nameEs: 'Capoeira', status: 'A'),
    Modality(id: 23, namePt: 'Natação', nameEn: 'Swimming', nameEs: 'Natación', status: 'A'),
    Modality(id: 24, namePt: 'Hidroginástica', nameEn: 'Water Aerobics', nameEs: 'Aquagym', status: 'A'),
    Modality(id: 25, namePt: 'Remo Indoor', nameEn: 'Indoor Rowing', nameEs: 'Remo Indoor', status: 'A'),
    Modality(id: 26, namePt: 'Escalada Indoor', nameEn: 'Indoor Climbing', nameEs: 'Escalada Indoor', status: 'A'),
    Modality(id: 27, namePt: 'TRX', nameEn: 'Suspension Training', nameEs: 'Entrenamiento en Suspensión', status: 'A'),
    Modality(id: 28, namePt: 'Slackline', nameEn: 'Slackline', nameEs: 'Slackline', status: 'A'),
    Modality(id: 29, namePt: 'Parkour', nameEn: 'Parkour', nameEs: 'Parkour', status: 'A'),
    Modality(id: 30, namePt: 'Escalada', nameEn: 'Climbing', nameEs: 'Escalada', status: 'A'),
    Modality(id: 31, namePt: 'Patinação', nameEn: 'Skating', nameEs: 'Patinaje', status: 'A'),
    Modality(id: 32, namePt: 'Ciclismo', nameEn: 'Cycling', nameEs: 'Ciclismo', status: 'A'),
    Modality(id: 33, namePt: 'Basquete', nameEn: 'Basketball', nameEs: 'Baloncesto', status: 'A'),
    Modality(id: 34, namePt: 'Futebol', nameEn: 'Soccer', nameEs: 'Fútbol', status: 'A'),
    Modality(id: 35, namePt: 'Futsal', nameEn: 'Indoor Soccer', nameEs: 'Fútbol Sala', status: 'A'),
    Modality(id: 36, namePt: 'Handebol', nameEn: 'Handball', nameEs: 'Balonmano', status: 'A'),
    Modality(id: 37, namePt: 'Vôlei', nameEn: 'Volleyball', nameEs: 'Voleibol', status: 'A'),
    Modality(id: 38, namePt: 'Beach Tennis', nameEn: 'Beach Tennis', nameEs: 'Tenis Playa', status: 'A'),
    Modality(id: 39, namePt: 'Tênis', nameEn: 'Tennis', nameEs: 'Tenis', status: 'A'),
    Modality(id: 40, namePt: 'Paddle', nameEn: 'Paddle', nameEs: 'Pádel', status: 'A'),
    Modality(id: 41, namePt: 'Esgrima', nameEn: 'Fencing', nameEs: 'Esgrima', status: 'A'),
    Modality(id: 42, namePt: 'Ginástica Rítmica', nameEn: 'Rhythmic Gymnastics', nameEs: 'Gimnasia Rítmica', status: 'A'),
    Modality(id: 43, namePt: 'Ginástica Artística', nameEn: 'Artistic Gymnastics', nameEs: 'Gimnasia Artística', status: 'A'),
    Modality(id: 44, namePt: 'Ginástica Acrobática', nameEn: 'Acrobatic Gymnastics', nameEs: 'Gimnasia Acrobática', status: 'A'),
    Modality(id: 45, namePt: 'Powerlifting', nameEn: 'Powerlifting', nameEs: 'Powerlifting', status: 'A'),
    Modality(id: 46, namePt: 'Strongman', nameEn: 'Strongman', nameEs: 'Strongman', status: 'A'),
    Modality(id: 47, namePt: 'Levantamento Olímpico', nameEn: 'Olympic Weightlifting', nameEs: 'Halterofilia Olímpica', status: 'A'),
    Modality(id: 48, namePt: 'Corrida de Obstáculos', nameEn: 'Obstacle Course Racing', nameEs: 'Carreras de Obstáculos', status: 'A'),
    Modality(id: 49, namePt: 'Dança Contemporânea', nameEn: 'Contemporary Dance', nameEs: 'Danza Contemporánea', status: 'A'),
    Modality(id: 50, namePt: 'Balé', nameEn: 'Ballet', nameEs: 'Ballet', status: 'A'),
    Modality(id: 51, namePt: 'Jazz Dance', nameEn: 'Jazz Dance', nameEs: 'Danza Jazz', status: 'A'),
    Modality(id: 52, namePt: 'Street Dance', nameEn: 'Street Dance', nameEs: 'Baile Urbano', status: 'A'),
    Modality(id: 53, namePt: 'Pole Dance', nameEn: 'Pole Dance', nameEs: 'Pole Dance', status: 'A'),
    Modality(id: 54, namePt: 'Ginástica Localizada', nameEn: 'Localized Gymnastics', nameEs: 'Gimnasia Localizada', status: 'A'),
    Modality(id: 55, namePt: 'Treinamento Militar', nameEn: 'Military Training', nameEs: 'Entrenamiento Militar', status: 'A'),
    Modality(id: 56, namePt: 'Corrida de Rua', nameEn: 'Street Running', nameEs: 'Carrera Callejera', status: 'A'),
    Modality(id: 57, namePt: 'Mountain Bike', nameEn: 'Mountain Biking', nameEs: 'Ciclismo de Montaña', status: 'A'),
    Modality(id: 58, namePt: 'Skate', nameEn: 'Skateboarding', nameEs: 'Skateboarding', status: 'A'),
    Modality(id: 59, namePt: 'Surfe', nameEn: 'Surfing', nameEs: 'Surf', status: 'A'),
    Modality(id: 60, namePt: 'Bodyboard', nameEn: 'Bodyboarding', nameEs: 'Bodyboard', status: 'A'),
    Modality(id: 61, namePt: 'Windsurf', nameEn: 'Windsurfing', nameEs: 'Windsurf', status: 'A'),
    Modality(id: 62, namePt: 'Kitesurf', nameEn: 'Kitesurfing', nameEs: 'Kitesurf', status: 'A'),
    Modality(id: 63, namePt: 'Canoagem', nameEn: 'Canoeing', nameEs: 'Piragüismo', status: 'A'),
    Modality(id: 64, namePt: 'Escalada em Rocha', nameEn: 'Rock Climbing', nameEs: 'Escalada en Roca', status: 'A'),
    Modality(id: 65, namePt: 'Tiro com Arco', nameEn: 'Archery', nameEs: 'Tiro con Arco', status: 'A'),
    Modality(id: 66, namePt: 'Corrida em Trilha', nameEn: 'Trail Running', nameEs: 'Carrera de Montaña', status: 'A'),
    Modality(id: 67, namePt: 'Corrida de Orientação', nameEn: 'Orienteering', nameEs: 'Orientación', status: 'A'),
    Modality(id: 68, namePt: 'Equitação', nameEn: 'Horse Riding', nameEs: 'Equitación', status: 'A'),
    Modality(id: 69, namePt: 'Atletismo', nameEn: 'Athletics', nameEs: 'Atletismo', status: 'A'),
    Modality(id: 70, namePt: 'Marcha Atlética', nameEn: 'Race Walking', nameEs: 'Marcha Atlética', status: 'A'),
    Modality(id: 71, namePt: 'Salto com Vara', nameEn: 'Pole Vault', nameEs: 'Salto con Pértiga', status: 'A'),
    Modality(id: 72, namePt: 'Salto em Altura', nameEn: 'High Jump', nameEs: 'Salto de Altura', status: 'A'),
    Modality(id: 73, namePt: 'Arremesso de Peso', nameEn: 'Shot Put', nameEs: 'Lanzamiento de Bala', status: 'A'),
    Modality(id: 74, namePt: 'Lançamento de Dardo', nameEn: 'Javelin Throw', nameEs: 'Lanzamiento de Jabalina', status: 'A'),
    Modality(id: 75, namePt: 'Lançamento de Disco', nameEn: 'Discus Throw', nameEs: 'Lanzamiento de Disco', status: 'A'),
    Modality(id: 76, namePt: 'Corrida de Revezamento', nameEn: 'Relay Race', nameEs: 'Carrera de Relevo', status: 'A'),
    Modality(id: 77, namePt: 'Treinamento Pós-Parto', nameEn: 'Postpartum Training', nameEs: 'Entrenamiento Postparto', status: 'A'),
    Modality(id: 78, namePt: 'Treinamento Pré-Natal', nameEn: 'Prenatal Training', nameEs: 'Entrenamiento Prenatal', status: 'A'),
    Modality(id: 79, namePt: 'Treinamento para Terceira Idade', nameEn: 'Senior Training', nameEs: 'Entrenamiento para Mayores', status: 'A'),
    Modality(id: 80, namePt: 'Treinamento Infantil', nameEn: 'Kids Training', nameEs: 'Entrenamiento Infantil', status: 'A'),
    Modality(id: 81, namePt: 'Treinamento Corporativo', nameEn: 'Corporate Training', nameEs: 'Entrenamiento Corporativo', status: 'A'),
    Modality(id: 82, namePt: 'Reabilitação Física', nameEn: 'Physical Rehabilitation', nameEs: 'Rehabilitación Física', status: 'A'),
    Modality(id: 83, namePt: 'Prevenção de Lesões', nameEn: 'Injury Prevention', nameEs: 'Prevención de Lesiones', status: 'A'),
    Modality(id: 84, namePt: 'Condicionamento Físico', nameEn: 'Physical Conditioning', nameEs: 'Acondicionamiento Físico', status: 'A'),
    Modality(id: 85, namePt: 'Core Training', nameEn: 'Core Training', nameEs: 'Entrenamiento de Core', status: 'A'),
    Modality(id: 86, namePt: 'Resistência Cardiorrespiratória', nameEn: 'Cardiorespiratory Endurance', nameEs: 'Resistencia Cardiorrespiratoria', status: 'A'),
    Modality(id: 87, namePt: 'Força Muscular', nameEn: 'Muscular Strength', nameEs: 'Fuerza Muscular', status: 'A'),
    Modality(id: 88, namePt: 'Flexibilidade', nameEn: 'Flexibility', nameEs: 'Flexibilidad', status: 'A'),
    Modality(id: 89, namePt: 'Velocidade', nameEn: 'Speed', nameEs: 'Velocidad', status: 'A'),
    Modality(id: 90, namePt: 'Agilidade', nameEn: 'Agility', nameEs: 'Agilidad', status: 'A'),
    Modality(id: 91, namePt: 'Coordenação Motora', nameEn: 'Motor Coordination', nameEs: 'Coordinación Motora', status: 'A'),
    Modality(id: 92, namePt: 'Equilíbrio', nameEn: 'Balance', nameEs: 'Equilibrio', status: 'A'),
    Modality(id: 93, namePt: 'Propriocepção', nameEn: 'Proprioception', nameEs: 'Propiocepción', status: 'A'),
    Modality(id: 94, namePt: 'Biomecânica do Movimento', nameEn: 'Movement Biomechanics', nameEs: 'Biomecánica del Movimiento', status: 'A'),
    Modality(id: 95, namePt: 'Análise Postural', nameEn: 'Postural Analysis', nameEs: 'Análisis Postural', status: 'A'),
    Modality(id: 96, namePt: 'Ergonomia', nameEn: 'Ergonomics', nameEs: 'Ergonomía', status: 'A'),
    Modality(id: 97, namePt: 'Psicomotricidade', nameEn: 'Psychomotricity', nameEs: 'Psicomotricidad', status: 'A'),
    Modality(id: 98, namePt: 'Educação Física Escolar', nameEn: 'School Physical Education', nameEs: 'Educación Física Escolar', status: 'A'),
    Modality(id: 99, namePt: 'Atividades Recreativas', nameEn: 'Recreational Activities', nameEs: 'Actividades Recreativas', status: 'A'),
    Modality(id: 100, namePt: 'Jogos Cooperativos', nameEn: 'Cooperative Games', nameEs: 'Juegos Cooperativos', status: 'A'),
    Modality(id: 101, namePt: 'Exergames', nameEn: 'Exergames', nameEs: 'Exergames', status: 'A'),
    Modality(id: 102, namePt: 'Atividades ao Ar Livre', nameEn: 'Outdoor Activities', nameEs: 'Actividades al Aire Libre', status: 'A'),
  ];
}
