// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQx3sToFBfrd61VtPCmOrBn10r0g4i2tA',
    appId: '1:1029067098489:web:1d5b9a4e56045c256187a8',
    messagingSenderId: '1029067098489',
    projectId: 'gymble-8727e',
    authDomain: 'gymble-8727e.firebaseapp.com',
    storageBucket: 'gymble-8727e.firebasestorage.app',
    measurementId: 'G-2L8VZEHDKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_hTH_8q2vvEiRXrT3Xa0Op1PW9v3Arc',
    appId: '1:1029067098489:android:3f7c16afae51f2696187a8',
    messagingSenderId: '1029067098489',
    projectId: 'gymble-8727e',
    storageBucket: 'gymble-8727e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Yc1K83I-wRU4B0xG6wC4_-XWa6qsGRI',
    appId: '1:1029067098489:ios:20d636578db696296187a8',
    messagingSenderId: '1029067098489',
    projectId: 'gymble-8727e',
    storageBucket: 'gymble-8727e.firebasestorage.app',
    androidClientId: '1029067098489-eck7pcplh9dvje5l7t2hvsn8u8atja47.apps.googleusercontent.com',
    iosClientId: '1029067098489-u750mlme496jtnbakt6ft3qs9pvfnvjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.treinadorpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Yc1K83I-wRU4B0xG6wC4_-XWa6qsGRI',
    appId: '1:1029067098489:ios:20d636578db696296187a8',
    messagingSenderId: '1029067098489',
    projectId: 'gymble-8727e',
    storageBucket: 'gymble-8727e.firebasestorage.app',
    androidClientId: '1029067098489-eck7pcplh9dvje5l7t2hvsn8u8atja47.apps.googleusercontent.com',
    iosClientId: '1029067098489-u750mlme496jtnbakt6ft3qs9pvfnvjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.treinadorpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQx3sToFBfrd61VtPCmOrBn10r0g4i2tA',
    appId: '1:1029067098489:web:49390cdbf0fabb406187a8',
    messagingSenderId: '1029067098489',
    projectId: 'gymble-8727e',
    authDomain: 'gymble-8727e.firebaseapp.com',
    storageBucket: 'gymble-8727e.firebasestorage.app',
    measurementId: 'G-JEF6GQY7M7',
  );
}